version: '3.8'  # Use a modern Compose file version

services:
  neo4j:
    build: ./neo4j
    container_name: neo4j
    volumes:
      - ./volumes/neo4j-cypher:/cypher  # Directory for Cypher queries
      - ./volumes/neo4j-data:/data  # Persist data using a named volume
      - ./volumes/neo4j-logs:/logs  # Store logs persistently
      - ./utils:/utils  # Plugins or utilities for Neo4j
    ports:
      - "7474:7474"  # Neo4j HTTP
      - "7687:7687"  # Neo4j Bolt

  modeling:
    build: ./modeling
    container_name: modeling
    ports:
      - "5000:5000"
    depends_on:
      - neo4j
    volumes:
      - ./streamlit:/streamlit  # App code or data shared with Streamlit

  streamlit:
    build: ./streamlit
    container_name: streamlit
    ports:
      - "8501:8501"
    depends_on:
      - neo4j  # Ensure Neo4j starts before Streamlit
      - modeling
    volumes:
      - ./streamlit:/streamlit  # Streamlit application code
      - ../modeling/models:/models  # Access models from the modeling service

volumes:
  neo4j-data:  # Named volume for Neo4j data
  neo4j-logs:  # Named volume for Neo4j logs
  neo4j-cypher:  # Named volume for Cypher queries files






# services:
#   neo4j:
#     build: ./neo4j
#     container_name: neo4j
#     volumes:
#       - /cypher:/cypher  # Directory for Cypher queries
#       - /data:/data  # Persist data on the host machine
#       - /logs:/logs  # Log files on the host
#       - /utils:/utils  # Plugins for Neo4j
#     ports:
#       - "7474:7474"  # Neo4j HTTP
#       - "7687:7687"  # Neo4j Bolt

#   modeling:
#     build: ./modeling
#     container_name: modeling  
#     ports:
#       - "5000:5000" 
#     depends_on:
#       - neo4j
#     volumes:
#       - ./streamlit:/streamlit   

#   streamlit:
#     build: ./streamlit
#     container_name: streamlit
#     ports:
#       - "8501:8501"
#     depends_on:
#       - neo4j         # Ensure Neo4j starts before Streamlit
#       - modeling
#     volumes:
#       - ./streamlit:/streamlit     
#       - ../modeling/models:/models          # Mount the Streamlit app code