version: '3.9'

services:
  neo4j:
    build: ./neo4j
    volumes:
      - ./data:/data  # Persist data on the host machine
      - ./logs:/logs  # Log files on the host
      - ./import:/import  # Directory for importable data
      - ./plugins:/plugins  # Plugins for Neo4j
      - ./conf:/var/lib/neo4j/conf  # Custom config for Neo4j
    ports:
      - 7474:7474  # Neo4j HTTP
      - 7687:7687  # Neo4j Bolt
    # entrypoint:
    #   - "/usr/local/bin/build_db.sh"  # Change if you want a different entrypoint

  streamlit:
    build: ./app
    container_name: app
    ports:
      - "8501:8501"   # Expose Streamlit app on port 8501
    depends_on:
      - neo4j         # Ensure Neo4j starts before Streamlit
    volumes:
      - ./app:/app          # Mount the Streamlit app code

    # environment:
    #   - NEO4J_AUTH=neo4j/cyp450kg  # Replace with your actual password
    